### ISSUE TITLE
File Structure

### ISSUE THREAD

**Issue by rasensio1** [pkcsecurity/brevity#1]
The folder scturcture for clj / cljs source code seems strange, with separate 'src' directories. `src/` and `src-cljs/`.
![image](https://user-images.githubusercontent.com/12215523/39609283-a11f3ba6-4efc-11e8-81dc-5d8d176e5718.png)

I have run across projects which use `src/project-name/clj/` and `src/project-name/cljs/`

Also: `src/clj/project-name/...` and `src/cljs/project-name/...` 
* `lein new reagent myapp` uses this one

I guess the benefit would be not having to have the project name twice in the file structure.
And then, if we bring in a `test/` directory (and it mirrors the `src/` directory) we also don't have to repeat the project name between the cljs and clj tests.

**Comment by weltan** [comment]
@rasensio1 yeah, add something here! :)

**Comment by rasensio1** [comment]
Also, it seems redundant that we have `cljs-src/projectname/cljs`
![screen shot 2018-05-04 at 9 46 45 am](https://user-images.githubusercontent.com/12215523/39640531-18d0fcf6-4f80-11e8-8654-2128254ea1b2.png)
