### ISSUE TITLE
I don't want the tool-src folder in the new project I create

### ISSUE THREAD

**Issue by spencerreeves** [pkcsecurity/brevity#17]
When I create a new project using the brevity template, a folder is added to the project under the base directory -> [project]/tool-src. This directory seems to include information on the template used to create the project, but is useless to me post creation.

**Comment by jmdx** [comment]
It looks like this directory is intended to provide some tooling for after the project is created.  So theoretically through the course of development, you could run something like:

**Comment by spencerreeves** [comment]
Ohhh, got it. Would this have to occur while the newly created app is still under the root `brevity` folder? Or could I run this command after I moved it, say during active development.

**Comment by jmdx** [comment]
You could run it after a long stretch of active development.  I think the intended use case is to set the project up in such a way that any time a developer wants to create a models file, they can just run that command.
